### ISSUE TITLE
秘钥泄露

### ISSUE THREAD

**Issue by moreant** [mxy493/TCB#1]
直接泄露key.json不太好吧

https://github.com/mxy493/TCB/blob/d98ecd173f09754e28dd853bedabb4912c1d5f34/cloudfunctions/login/key.json#L1

**Comment by mxy493** [comment]
> 直接泄露key.json不太好吧
> 
> https://github.com/mxy493/TCB/blob/d98ecd173f09754e28dd853bedabb4912c1d5f34/cloudfunctions/login/key.json#L1

确实是这样，没事，任务做完就删库跑路了
